title: Aakanksha Dutta
logo: "/images/logo.png?raw=true"
description: >
  First description
  <br><br>
  Second description
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0
